### ISSUE TITLE
TaskSequence completes somewhat

### ISSUE THREAD

**Issue by Ravenofozz** [windows-admins/Intune#2]
This TS adds the device to Autopilot but does not show under Intune devices and also does not boot to OOBE after completing successfully. Therefore I cannot log into the device with a tenant account. I have tried adding script 3 to the TS step as a defined script instead of calling from the TS package, still no luck. Does anyone have any ideas?

**Comment by jshackelford9375** [comment]
The devices will not show under intune devices, it will show in Autopilot Devices. This blade https://endpoint.microsoft.com/#blade/Microsoft_Intune_Enrollment/AutoPilotDevicesBlade 

As far as the Script 3 I haven't heard any other issues, I've had several others test with success.

**Comment by unkownuser231** [comment]
please let us know how to upload device hash with multiple group tag and script2 how to suppress Microsoft portal login wizard during SCCM task sequence
